const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const WRITE_TITLE = 'WRITE_TITLE';
const CREATE_COMMENT = 'CREATE_COMMENT';
const UPDATE_COMMENT = 'UPDATE_COMMENT';

export { INCREMENT, DECREMENT, WRITE_TITLE, CREATE_COMMENT, UPDATE_COMMENT };
