const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const WRITE_TITLE = 'WRITE_TITLE';
const CREATE_COMMENT = 'CREATE_COMMENT';
const UPDATE_COMMENT = 'UPDATE_COMMENT';
const DELETE_COMMENT = 'DELETE_COMMENT';
const LOAD_COMMENTS = 'LOAD_COMMENTS';
const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';

export {
  INCREMENT,
  DECREMENT,
  WRITE_TITLE,
  CREATE_COMMENT,
  UPDATE_COMMENT,
  DELETE_COMMENT,
  LOAD_COMMENTS,
  LOADER_DISPLAY_ON,
  LOADER_DISPLAY_OFF,
};
